<?php

/**
 * @file
 * Provides basic hook implementations for the Salutation module.
 */

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string|void
 */
function nm_salutation_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  // Provides help text to the user via the UI.
  switch ($route_name) {
    case 'help.page.nm_salutation':
      $output = t('
        <h2>Salutation Message.</h2>
        <h3>Use this module to provide a salutation message to your end user.</h3>
        ');
      return $output;
  }
}

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array[]
 */
function nm_salutation_theme($existing, $type, $theme, $path) {
  return [
    'salutation_text' => [
      'variables' => [
          'salutation_text' => '',
      ],
      'template' => 'salutation',
    ],
  ];
}
