nm_salutation.settings:
  type: config_object
  label: 'Salutation settings'
  mapping:
    morning_salutation:
      type: text
      label: 'Morning salutation:'
      translatable: true
    afternoon_salutation:
      type: text
      label: 'Afternoon salutation:'
      translatable: true
    evening_salutation:
      type: text
      label: 'Evening salutation:'
      translatable: true
